package de.footballmanager.backend.enumeration;

public enum Position {

    GOALY, STOPPER, LEFT_DEFENDER, RIGHT_DEFENDER, DEFENSIVE_MIDFIELDER, OFFENSIVE_MIDFIELDER, RIGHT_MIDFIELDER,
    LEFT_MIDFIELDER, LEFT_WINGER, RIGHT_WINGER, STRIKER;
}
